"""group can be nullable

Revision ID: 583c9c07d67a
Revises: a6c960e2bf90
Create Date: 2023-11-27 02:46:06.482224

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "583c9c07d67a"
down_revision: Union[str, None] = "a6c960e2bf90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "group_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "group_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
