name: test

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres_main:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: user_manager
        ports:
          - 5432:5432

      redis_main:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.5.1'
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Set up environment variables
        run: |
          echo "LOGGING_LEVEL=DEBUG" >> .env
          echo "DATABASE=postgresql+asyncpg" >> .env
          echo "DB_USER=postgres" >> .env
          echo "PASSWORD=postgres" >> .env
          echo "HOST=localhost" >> .env
          echo "PORT=5432" >> .env
          echo "DB_NAME=user_manager" >> .env
          echo "TEST_DB_NAME=test_user_manager" >> .env
          echo "SECRET_KEY=d4954e9fc9d428d6f3cd1e2b9776aeeef91cc94abc879f940b129bcbbc33ef5a" >> .env
          echo "ALGORITHM=HS256" >> .env
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=30" >> .env
          echo "REFRESH_TOKEN_EXPIRE_DAYS=2" >> .env
          echo "REDIS_URL=redis://localhost:6379?decode_responses=True" >> .env
          echo "TEST_REDIS_URL=redis://localhost:6379/2?decode_responses=True" >> .env
          echo "SMTP_SERVER=mail.address.com" >> .env
          echo "SMTP_PORT=900" >> .env
          echo "SMTP_USERNAME=polybank@andersenlab.com" >> .env
          echo "SMTP_PASSWORD=smtp_password" >> .env
          echo "MODE=DEV" >> .env
          echo "USER_ID=7cac12b6-219c-4117-889b-a22c00b8b858" >> .env
          echo "TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiN2NhYzEyYjYtMjE5Yy00MTE3LTg4OWItYTIyYzAwYjhiODU4IiwiZXhwIjoxNzA2MDUyMzYzfQ.IM5jNPZr-5eGQI0cw3qYRHNr41jipmDxzzPG746a0xE" >> .env

      - name: Run tests
        env:
          DB_NAME: ${{ env.TEST_DB_NAME }}
          TEST_REDIS_URL: ${{ env.TEST_REDIS_URL }}
          POSTGRES_PASSWORD: ${{ env.PASSWORD }}
        run: poetry run pytest
